<?php
/**
 * Страница "Список служб".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью расширения модуля веб-приложения RosGear.
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */
?>
<article>
    <h1>Список служб</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/grid.png' ?>" />
    </div>
    <p>Список отображает все доступные службы (сервисы) фреймворка.</p>
    <h2>Столбцы списка</h2>
    <ul class="g-help-list">
        <li><b>Имя</b> Имя службы;</li>
        <li><b>Класс.</b> Класс-служба в фреймворке;</li>
        <li><b>В автозагрузке Frontend.</b> При установленном флаге служба доступна для обработки запросов от frontend-части (сайт). Автозагрузка поддерживается не для всех служб;</li>
        <li><b>В автозагрузке Backend.</b> При установленном флаге служба доступна для обработки запросов от backend-части (панель управления). Автозагрузка поддерживается не для всех служб;</li>
        <li><b>Конфигуратор.</b> При установленном флаге служба использует отдельный файл конфигурации (конфигуратор) для хранения настроек.</li>
    </ul>

    <h2>Панель инструментов</h2>
    <ul class="g-help-list">
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/cleanup.svg' ?>" /> <b>Очистить.</b> Сбрасывает автозагрузку служб для сайта (frontend) и Панели управления (backend);</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/refresh.svg' ?>" /> <b>Обновить.</b> Обновляет список служб;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-profiling-off.svg' ?>" /> <b>Профилирование записи.</b> Разворачивает или сворачивает Панель навигации для отображения информации о выбранной службе;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/help.svg' ?>" /> <b>Справка.</b> Вызывает окно справочной информации для текущего списка;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/search.svg' ?>" /> <b>Поиск.</b> Вызывает форму поиска служб в списке.</li>
    </ul>
</article>