<?php
/**
 * Страница "Список служб".
 * 
 * Локализации по умолчанию.
 * 
 * Этот файл является частью расширения модуля веб-приложения RosGear.
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */
?>
<article>
    <h1>Service list</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/grid.png' ?>" />
    </div>
    <p>The list displays all available framework services.</p>
    <h2>List columns</h2>
    <ul class="g-help-list">
        <li><b>Name</b> Service name;</li>
        <li><b>Class.</b> Service class in the framework;</li>
        <li><b>In Frontend autoload.</b> When the flag is set, the service is available to process requests from the frontend (the website). Automatic startup is not supported for all services;</li>
        <li><b>In Backend autoload.</b> When the flag is set, the service is available to process requests from the backend (control panel). Automatic startup is not supported for all services;</li>
        <li><b>Configurator.</b> When the flag is set, the service uses a separate configuration file (configurator) to store settings.</li>
    </ul>

    <h2>Toolbar</h2>
    <ul class="g-help-list">
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/cleanup.svg' ?>" /> <b>Clear.</b> Resets the service autostart for the site (frontend) and the Control Panel (backend);</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/refresh.svg' ?>" /> <b>Refresh.</b> Refresh the list of services;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-profiling-off.svg' ?>" /> <b>Record profiling.</b> Expands or collapses the navigation panel to display information about the selected service;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/help.svg' ?>" /> <b>Help.</b> Opens the reference information window for the current list;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/search.svg' ?>" /> <b>Search.</b> Opens the service search form in the list.</li>
    </ul>
</article>